os: unstable
shallow_clone: true

environment:
  global:
    QTDIR: C:\Qt\Qt5.3.2\5.3\msvc2013_opengl
    NSIS_ROOT: C:\nsis

install:
  - 'appveyor DownloadFile "http://sunet.dl.sourceforge.net/project/nsis/NSIS 2/2.46/nsis-2.46-setup.exe" -FileName nsissetup.exe'
  - 'nsissetup.exe /S /D=%NSIS_ROOT%'
  - set PATH=%PATH%;%QTDIR%\bin
  - ls C:\Qt
  - ls C:\Qt\Qt5.3.2\5.3
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86

build_script:
  - qmake tiled.pro
  - nmake
