os: unstable
shallow_clone: true

environment:
  global:
    QTDIR: C:\Qt\Qt5.3.2\5.3\mingw482_32
    NSIS_ROOT: C:\nsis

install:
  - appveyor DownloadFile "http://sunet.dl.sourceforge.net/project/nsis/NSIS 2/2.46/nsis-2.46-setup.exe" -FileName nsissetup.exe
  - nsissetup /S /D=%NSIS_ROOT%
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - set VERSION=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%
  - FOR /F "tokens=*" %%i in ('%GIT% describe') do SET COMMITNOW=%%i
  - echo Building Tiled daily %VERSION%... (from %COMMITNOW%)
  - qmake tiled.pro "CONFIG+=release" "QMAKE_CXXFLAGS+=-DBUILD_INFO_VERSION=%COMMITNOW%"
  - mingw32-make
